changelog:
  categories:
    - title: ✨ New features ✨
      labels:
        - '✨ feature ✨'
    - title: 🐛 Bugs fix 🐛
      labels:
        - '🐛 bug 🐛'
    - title: 📝 Documentation 📝
      labels:
        - '📝 documentation 📝'  